### ISSUE TITLE
Why not use the Authorization header?

### ISSUE THREAD

**Issue by promontis** [nhi/react-hotchocolate-subscription#1]
In https://github.com/nhi/react-hotchocolate-subscription/blob/6a1f6b0b2439154c0356d2062274fbbd86a44e58/React/src/utils/apolloprovider.js#L24 you are using the `authToken` header, right? Why not use the `Authorization` header so that it matches how queries and mutations are (probably) sent?

**Comment by PetterRein** [comment]
I used the authToken header here: because it is what PascalSenn uses in his gist about Apollo + HotChocolate subscriptions. It is possible to change this to `return { Authorization: "${token}" }` 

but then you have to change:
https://github.com/nhi/react-hotchocolate-subscription/blob/6a1f6b0b2439154c0356d2062274fbbd86a44e58/HotChocolate/AuthenticationSocketInterceptor.cs#L16

to `public static readonly string WEBOCKET_PAYLOAD_AUTH_KEY = "Authorization";`

from my quick testing now it does not change anything and you still have to inject the context: `context.ContextData["ClaimsPrincipal"] = webSocketContext.User;`

**Comment by promontis** [comment]
@PetterRein Great! I'll use the `Authorization` header then 🤗
